name: "Update wiki"
description: "This action updates wiki repository with changes made in base repository"
inputs:
  token:
    description: "Github token"
    required: true
  runs:
    using: "composite"
    steps:
      - run: echo Hello
      shell: bash
