name: GitHub Actions update wiki
run-name: ${{ github.actor }} is update wiki 🚀🚀
on: [push]

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: wiki
        uses: ./docs/updateWiki/action.yml
        env:
          tokena: ${{ secrets.GITHUB_TOKEN }}