name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Plantuml
        uses: grassedge/generate-plantuml-action@v1.5
      - run: echo "🎉 here"
      - run: pwd
      - run: ls
      - run: pwd
