name: GitHub Actions Diagrams
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: plantuml
        id: plantuml
        uses: grassedge/generate-plantuml-action@master
        with:
          path: docs/diagram
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}